# Generated by Django 4.2.4 on 2023-09-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(null=True, to='blog.comment', verbose_name='Коментарі'),
        ),
    ]
