# Generated by Django 4.2.4 on 2023-10-01 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0014_userprofile_email_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('comment_count', models.IntegerField(default=0)),
                ('post_count', models.IntegerField(default=0)),
                ('forum_posts', models.IntegerField(default=0)),
                ('blog_posts', models.IntegerField(default=0)),
                ('days_on_site', models.IntegerField(default=0)),
                ('reputation', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
